# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27546c09c840265bc1ed2d59cc812bbc52d3ccd8138de49a9a350799a7275f73570fe07c90e1849438e98b63277c329fc27b490f60a056b80cbb0ff6ba4a652c

test:
  secret_key_base: fab02dc889891eda8daab01c37d9e04ea813bf7090ba6fec034b9c34a62db7cf77ef40fd29bbf429125f9d4115cc209210665b677510514bc6c54d54ac662087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
